//! UUIDs for the browse group identifiers module.

// This file is auto-generated by the update_uuids application.
// Based on https://bitbucket.org/bluetooth-SIG/public.git
// Commit hash: 8c192a8effd1574d0c83e72ad91407511bcad209

use super::BluetoothUuid16;

/// Bluetooth browse group identifiers UUID.
///
/// `0x1002` PublicBrowseRoot
pub const PUBLIC_BROWSE_ROOT: BluetoothUuid16 = BluetoothUuid16::new(0x1002);
